### ISSUE TITLE
Binder version prompts "@jupyterlab/latex needs to be included in build"

### ISSUE THREAD

**Issue by psychemedia** [jupyterlab/jupyterlab-latex#100]
Running on binderhub via the Binder button, I get the prompt:

```
Build Recommended
JupyterLab build is suggested:
@jupyterlab/latex needs to be included in build
```

accepting reloads the page and then just offers the same prompt again. 

Selecting the `.tex` document and then right clicking on it only shows the *Create Console for Editor* and now the *Show LaTeX Preview* option.

Chrome 69.0.3497

**Comment by ian-r-rose** [comment]
Sorry for the slow response @psychemedia. I'm not sure what the issue could be just yet: what versions of node/npm do you have?

Perhaps some of the suggestions [here](https://github.com/jupyterlab/jupyterlab/issues/5350) could be useful as well.

**Comment by psychemedia** [comment]
@ian-r-rose no idea... I am clicking the Binderhub button on the repo `README` / homepage and getting the error...

It seems to go in a loop, prompting me with `Build Complete
Build successfully completed, reload page?: Cancel / Reload` and if I click reload it spinny things then prompts `JupyterLab build is suggested:
@jupyterlab/latex needs to be included in build: Cancel / Build` and if I click `Build` if spinny things and goes back to the `Build Complete` popup.

**Comment by ian-r-rose** [comment]
Oops, my mistake, I missed that you were using Binder. I probably let that go stale. Checking now...

**Comment by ian-r-rose** [comment]
Yep, that was a *really* old version. Let me try to update it...

**Comment by ian-r-rose** [comment]
Thanks for bringing this to my attention @psychemedia, I've just updated the binder versions -- hopefully it should work now.

**Comment by psychemedia** [comment]
Great, works fine now; thanks.
