### ISSUE TITLE
how to update this jupyterlab-extension?

### ISSUE THREAD

**Issue by PhilosopherZ** [jupyterlab/jupyterlab-latex#101]
I don't know **how to update this jupyterlab-extension？**

**Comment by ian-r-rose** [comment]
What versions of jupyterlab and jupyterlab-latex do you have installed?
You can upgrade the package by entering
```
jupyter labextension upgrade @jupyterlab/latex
```

**Comment by PhilosopherZ** [comment]
@ian-r-rose thanks for your answer!
![image](https://user-images.githubusercontent.com/33093881/47634518-be55d280-db8c-11e8-8334-72b821d45bc0.png)
but there is an error!
![image](https://user-images.githubusercontent.com/33093881/47634631-299fa480-db8d-11e8-81a5-6e31c7fea6d9.png)

**Comment by ian-r-rose** [comment]
Whoops, typo above. I meant `jupyter labextension update @jupyterlab/latex`. Are you sure you have the labextension installed? Remember that there is both a server extension and a lab extension for this functionality.

**Comment by bollwyvl** [comment]
As of #171, the "prebuilt" labextension approach is recommended, which install both parts of the extension (lab and server) and does not require nodejs.
