### ISSUE TITLE
Allow install to use node in PATH

### ISSUE THREAD

**Issue by kylebarron** [jupyterlab/jupyterlab-latex#104]
I'm getting an error when installing because it's trying to use the `node` executable in my conda directory instead of the one on my PATH. I didn't install node from Conda, so I'm assuming that's a dependency of some other program.

The node from Conda is a lower version:
```
> ~/local/anaconda3/bin/node --version
v6.11.2
```

The node on my PATH is a higher version:
```
> node --version
v10.13.0
```

Especially when the error message says that node can be downloaded manually, I think the install should check if the node on the PATH is of a sufficiently high version.

Full install traceback:
```
> jupyter labextension install @jupyterlab/latex --debug
Searching ['/disk/agedisk3/medicare.work/doyle-DUA51929/barronk-dua51929/medicare-modernization/harmonization/code', '/disk/homedirs/barronk-dua51929/.jupyter', '/homes/nber/barronk-dua51929/local/anaconda3/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Looking for jupyter_config in /etc/jupyter
Looking for jupyter_config in /usr/local/etc/jupyter
Looking for jupyter_config in /homes/nber/barronk-dua51929/local/anaconda3/etc/jupyter
Looking for jupyter_config in /disk/homedirs/barronk-dua51929/.jupyter
Looking for jupyter_config in /disk/agedisk3/medicare.work/doyle-DUA51929/barronk-dua51929/medicare-modernization/harmonization/code
Traceback (most recent call last):

  File "/homes/nber/barronk-dua51929/local/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 1483, in _node_check
    output = subprocess.check_output([node, 'node-version-check.js'], cwd=HERE)

  File "/homes/nber/barronk-dua51929/local/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout

  File "/homes/nber/barronk-dua51929/local/anaconda3/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)

subprocess.CalledProcessError: Command '['/homes/nber/barronk-dua51929/local/anaconda3/bin/node', 'node-version-check.js']' returned non-zero exit status 1.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/homes/nber/barronk-dua51929/local/anaconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 77, in start
    ans = self.run_task()

  File "/homes/nber/barronk-dua51929/local/anaconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 106, in run_task
    for arg in self.extra_args

  File "/homes/nber/barronk-dua51929/local/anaconda3/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 106, in <listcomp>
    for arg in self.extra_args

  File "/homes/nber/barronk-dua51929/local/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 217, in install_extension
    _node_check(logger)

  File "/homes/nber/barronk-dua51929/local/anaconda3/lib/python3.6/site-packages/jupyterlab/commands.py", line 1489, in _node_check
    raise ValueError(msg)

ValueError: Please install nodejs >=6.11.5 before continuing. nodejs may be installed using conda or directly from the nodejs website.


Errored, use --debug for full output:
ValueError: Please install nodejs >=6.11.5 before continuing. nodejs may be installed using conda or directly from the nodejs website
```

**Comment by kylebarron** [comment]
Apparently I can't install any lab extension, so maybe this is an issue for jupyterlab core?

**Comment by ian-r-rose** [comment]
Yes, installing any JupyterLab extension requires a sufficiently recent version of `node`. I'd recommend trying to update the one in your conda environment, or, failing that, removing it.

**Comment by kylebarron** [comment]
Understood. Is it a bug that it doesn't choose the `node` on my PATH?

**Comment by ian-r-rose** [comment]
In general, binaries that are in a conda environment will be found first (conda prepends their path to your overall `PATH`), so I would say it is working as intended.

**Comment by kylebarron** [comment]
The `node` called from within `labextension install`, according to the traceback above, is
```
/homes/nber/barronk-dua51929/local/anaconda3/bin/node
```
which is a different path than
```
~/local/bin/node
```
```
> echo $HOME
/homes/nber/barronk-dua51929
```

**Comment by kylebarron** [comment]
After running `conda install -c conda-forge nodejs`, the labextension install works correctly, but it _still_ chooses the `node` within the conda directory.
```
> jupyter labextension install @jupyterlab/latex

Node v10.8.0

> /homes/nber/barronk-dua51929/local/anaconda3/bin/npm pack @jupyterlab/latex
...
```

Given this, I think one of the two actions would be useful
1. JupyterLab was installed from Conda. So I think the Conda build should depend on `node`>= 6.11.5.
2. Switch to using the `node` on `PATH`

This seems like a general Jupyterlab issue. Should I post it on `jupyterlab/jupyterlab`?

**Comment by ian-r-rose** [comment]
Sure, please do. I think there are some prior issues regarding which environment the `jupyter` command uses (and I'm not entirely sure what the correct behavior is in this case), but I am unable to find them at the moment.

**Comment by bollwyvl** [comment]
As of #171, the "prebuilt" distribution mechanism is preferred, which does not require `nodejs`.
