### ISSUE TITLE
issue with document path

### ISSUE THREAD

**Issue by Swanson-Hysell** [jupyterlab/jupyterlab-latex#110]
This issue seems similar to #59, but is happening on a fresh pip install.

This error is thrown such that no document is compiled:
```
Request cannot be completed; no file at `/Users/Laurentia/build/0000_Github/Laurentia_Paleogeography/manuscript.tex`.
```

The correct path is:
`/Users/Laurentia/0000_Github/Laurentia_Paleogeography/manuscript.tex`.
so it seems to be looking for a build folder that doesn't exist.

**Comment by Kapral67** [comment]
What are your root_dir and notebook_dir strings set to in your config python file?

I fixed mine by matching the two strings even though notebook_dir is deprecated. It looks like this extension still uses notebook_dir based on #55.

**Comment by bob-ortiz** [comment]
@Kapral67 How did you match the root_dir and notebook_dir? Like, how does one find those two directories?

**Comment by Kapral67** [comment]
@bob-ortiz

In my `jupyter_lab_config.py`, I have it set like:

```python
c.ServerApp.root_dir = '/fully/qualified/path/to/directory/'
c.ServerApp.notebook_dir = c.ServerApp.root_dir
```

*Fair warning, I am not using the latest version of Jupyter Lab and this workaround is only accurate to versions up till whatever was latest Aug 9, 2021. I don't know if this is still necessary in the later versions.*

**Comment by jhgoebbert** [comment]
@Kapral67 Thank you for the work-around.  
I am using JupyterLab 3.6.5 with jupyterlab-latex 3.2.0 and still have to set `c.ServerApp.notebook_dir` if I set the root_dir explicitly:  
```
c.ServerApp.root_dir = '/'
c.ServerApp.notebook_dir = c.ServerApp.root_dir
```
