### ISSUE TITLE
Troubles with verison of jupyter lab

### ISSUE THREAD

**Issue by Galex1223** [jupyterlab/jupyterlab-latex#111]
Hi, I'm trying to install your package, but got some issues with versions.

It is mentioned in the readme that we need Jupyter lab version 1.0, so I went ahead and got jupyterlab==1.0.0.a1 because it seems to be the latest !

However, when I run : 
`jupyter labextension install @jupyterlab/latex`

I get : 
`Errored, use --debug for full output:`
`ValueError: This extension does not yet support the current version of JupyterLab.`

`Conflicting Dependencies:`
`JupyterLab              Extension              Package`
`>=1.0.0-alpha.3 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/application`
`>=1.0.0-alpha.3 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/apputils`
`>=1.0.0-alpha.3 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/docmanager`
`>=1.0.0-alpha.3 <2.0.0  >=0.19.1 <0.20.0       @jupyterlab/fileeditor`

Any insight as to how I should deal with this ?
Thank you and I hope I will be able to try you package !

**Comment by ian-r-rose** [comment]
Hi @Galex1223, sorry for the confusion! The code that is on `master` is currently targeting 1.0-alpha, but it has not been published yet. I'd recommend using the latest stable JupyterLab (v0.35), and installing the version for that: `jupyter labextension install @jupyterlab/latex@0.6.1`

Let me know if that helps.

**Comment by Galex1223** [comment]
Yep ! That did it ! Thank you very much @ian-r-rose !

Would you happen to know which version of jupyterlab-toc is compatible with jupyterlab 0.35.4 ? Or just point me to a general way of knowing without always asking a question ? 

And out of context, is there any plans for autocompletion and a more "complete" support of latex ?

**Comment by ian-r-rose** [comment]
For `@jupyterlab/toc` you will want `0.6.0`

**Comment by ian-r-rose** [comment]
Closing as answered, but feel free to comment further if you have more questions.

**Comment by Galex1223** [comment]
Thank you for the really fast answers ! If I may ask, what do you see as the future of this extension ?
