### ISSUE TITLE
Question: shell escape is disabled, so I can only detect \ifwindows.

### ISSUE THREAD

**Issue by ForKicks2** [jupyterlab/jupyterlab-latex#112]
Hi!

Pretty new new to the jupyterlab scene, but love the idea and this latex extension!

But I have run in to a problem where it wont build the pdf because:

>"Package ifplatform Warning: 
>    shell escape is disabled, so I can only detect \ifwindows."

>"./main.tex:12: Package minted Error: You must invoke LaTeX with the -shell-esca
>pe flag."

Is there a way to pass this command or change it in a config somewhere?

If its of importance I'm am running this jupyterlab with jupyterhub on Ubuntu 18.04

best regards

**Comment by ForKicks2** [comment]
In my first attempt I installed the extension  according to the README, and couldnt get shell-escape working. But for future reference, building from source 0.61 and passing then passing the:

> c.LatexConfig.shell_escape = "allow"

in the jupyter config fixed the issue.

**Comment by ian-r-rose** [comment]
Glad you got it working!
