### ISSUE TITLE
shell-escape in documentation

### ISSUE THREAD

**Issue by b-trav** [jupyterlab/jupyterlab-latex#120]
Great extension - thank you.

Could I suggest you place the text from [advanced.md](https://github.com/jupyterlab/jupyterlab-latex/blob/master/docs/advanced.md) in the ReadMe.md file? As it took me a while to get the markdown package working (which requires shell-escape).

I finally found the solution in this closed question: https://github.com/jupyterlab/jupyterlab-latex/issues/112

**Comment by ian-r-rose** [comment]
@b-trav Good idea, I think the README.md is not so long that we couldn't combine them.

Pull requests welcome :)

**Comment by b-trav** [comment]
Added pull request:
https://github.com/jupyterlab/jupyterlab-latex/pull/125
