### ISSUE TITLE
JupyterLab 2.0 Compability

### ISSUE THREAD

**Issue by belfhi** [jupyterlab/jupyterlab-latex#130]
Hello,
is it planned to update the extension for jupyterlab 2.0?

**Comment by Jeremiah-England** [comment]
@belfhi There appear to be some recent commits related to this: 6f000aec7dba092523bbe00bd676037c31a3ad51, 1484d07c37ed573e746d2cca0beb36129066056e

**Comment by ian-r-rose** [comment]
This has been published as `@jupyterlab/latex@2.0`
