### ISSUE TITLE
Un-pin JupyterLab in the binder environment

### ISSUE THREAD

**Issue by choldgraf** [jupyterlab/jupyterlab-latex#136]
Right now the Binder environment runs JupyterLab ~ .36 or so...that is super out-of-date, and we've gotten some [reports in Binder](https://github.com/binder-examples/latex/pull/9) about unexpected behavior with this package. We should un-pin or update the dependency and make sure that it works with the latest jupyterlab

**Comment by bollwyvl** [comment]
The update `pip`-based binder has (gah) `jupyterlab ~3.0` which _should_ remain accurate for the `3.x` line of this extension.
