### ISSUE TITLE
RuntimeError: JupyterLab-latex failed to build

### ISSUE THREAD

**Issue by ArnavHP18** [jupyterlab/jupyterlab-latex#139]
![c13bf3f3-7a9a-42c4-8d6b-24808e17ff48](https://user-images.githubusercontent.com/32594107/89320095-a9ca3680-d69e-11ea-8ebe-8d29fb4050d7.jpg)

JupyterLab version 2.2.2 and tried with older version 2.1.5 also.
Python 3.8.3
Installed jupyterlab_latex

[jupyterlab-debug-9olfwult.log](https://github.com/jupyterlab/jupyterlab-latex/files/5023367/jupyterlab-debug-9olfwult.log)

**Comment by nikhilshinde095** [comment]
facing the same issue

**Comment by Soothysay** [comment]
I am facing the same issue as well! Can we get some help?

**Comment by scottweitzner** [comment]
This was mostly likely related to issue #135 which was just resolved in the merge/tag related to MR #137. @ArnavHP18 @nikhilshinde095 @Soothysay can you confirm using the most recent version v2.0.1

**Comment by bollwyvl** [comment]
Given the complexity/weight of pdfjs, it's likely the "prebuilt" distribution (available as of 3.1.0) is the only one we can support on an on-going basis.

See https://github.com/jupyterlab/jupyterlab-latex/issues/154#issuecomment-928048027
