### ISSUE TITLE
Patch npm version 1.0.0 for "can't resolve 'worker-loader'" error related to pdfjs-dist

### ISSUE THREAD

**Issue by trybik** [jupyterlab/jupyterlab-latex#143]
I have setup that requires `jupyterlab<2.0`, which is not compatible with `@jupterlab/latex@2.0.1`, but there is a build error in `@jupterlab/latex@1.0.0` as in https://github.com/jupyterlab/jupyterlab-latex/pull/137 .

Would it be possible to do an analogous patch that pins the pdfjs-dist version and a corresponding 1.0.1 npm release?

**Comment by bioinfornatics** [comment]
👍

**Comment by bollwyvl** [comment]
Resolved as of https://github.com/jupyterlab/jupyterlab-latex/issues/154#issuecomment-928048027
