### ISSUE TITLE
failure when install latex for jupyter:'gbk' code can't decode byte

### ISSUE THREAD

**Issue by riverstill** [jupyterlab/jupyterlab-latex#145]
[jupyterlab-debug-2x_sq1_j.log](https://github.com/jupyterlab/jupyterlab-latex/files/5215763/jupyterlab-debug-2x_sq1_j.log)

**Comment by bollwyvl** [comment]
As of #171, the "prebuilt" distribution is recommended, which does not require `nodejs`.
