### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by joequant** [jupyterlab/jupyterlab-latex#147]
Hey this stuff is GREAT!!!!  I'm using this with beamer to create some slides

So some UI suggestions

* add a button that allows for creating a new .tex file from jupyterlab menus
* add a refresh button

**Comment by ktaletsk** [comment]
Hi @joequant, thanks for the suggestions. I am going to ask a couple questions about your suggestions:

1. There are currently two ways to create a new .tex file from JupyterLab UI.
    - Launcher icon 
![image](https://user-images.githubusercontent.com/8834829/135366498-2633818a-b777-4dc4-b47e-6eba12c663ee.png)
    - Main menu command 
![image](https://user-images.githubusercontent.com/8834829/135366453-00352b8a-e58e-4e6a-922e-b83ce290a838.png)
    Did you mean these 2 buttons, or something else?
2. What should the refresh button do?

**Comment by ktaletsk** [comment]
There wasn't any follow-up to the question, closing for now
