### ISSUE TITLE
Jupyterlab 3.0.0rcx, jupyterlab_latex 2.0.1 and latex 0.0.1

### ISSUE THREAD

**Issue by enriqueartal** [jupyterlab/jupyterlab-latex#152]
I cannot install jupyterlab_latex-2.0.1 via pip, last available version is 2.0.0; this version does not install with jupyterlab-3.0.0.rc10. On the other side a labextension latex 0.0.1 appears but when opening a latex file I do not see any special feature.

**Comment by joequant** [comment]
FYI I have a jupyterlab_latex package on my branch that works with 3.0

**Comment by bollwyvl** [comment]
Resolved, please see https://github.com/jupyterlab/jupyterlab-latex/issues/154#issuecomment-928048027.

In the future, it's _possible_ this extension will be updated to work with major RCs, but as a relatively niche extension with some tricky dependencies, it is likely it will lag... though hopefully not as long as this time!
