### ISSUE TITLE
Failure when running "jupyter labextension install @jupyterlab/latex"

### ISSUE THREAD

**Issue by halcatt** [jupyterlab/jupyterlab-latex#162]
Node v14.16.0

Yarn configuration loaded.
> /usr/local/bin/npm pack @jupyterlab/latex
npm notice 
npm notice 📦  @jupyterlab/latex@2.0.1
npm notice === Tarball Contents === 
npm notice 2.2kB  package.json            
npm notice 1.5kB  LICENSE                 
npm notice 3.0kB  README.md               
npm notice 746B   lib/error.d.ts          
npm notice 1.2kB  lib/error.js            
npm notice 637B   lib/index.d.ts          
npm notice 18.7kB lib/index.js            
npm notice 1.1kB  lib/pagenumber.d.ts     
npm notice 4.2kB  lib/pagenumber.js       
npm notice 3.8kB  lib/pdf.d.ts            
npm notice 17.3kB lib/pdf.js              
npm notice 401B   schema/plugin.json      
npm notice 600B   style/fit_dark.svg      
npm notice 600B   style/fit_light.svg     
npm notice 2.6kB  style/index.css         
npm notice 213B   style/next_dark.svg     
npm notice 213B   style/next_light.svg    
npm notice 210B   style/previous_dark.svg 
npm notice 210B   style/previous_light.svg
npm notice 450B   style/zoom_in_dark.svg  
npm notice 450B   style/zoom_in_light.svg 
npm notice 411B   style/zoom_out_dark.svg 
npm notice 411B   style/zoom_out_light.svg
npm notice === Tarball Details === 
npm notice name:          @jupyterlab/latex                       
npm notice version:       2.0.1                                   
npm notice filename:      jupyterlab-latex-2.0.1.tgz              
npm notice package size:  15.4 kB                                 
npm notice unpacked size: 61.3 kB                                 
npm notice shasum:        1553281405c97267ceda3c44ab23ecee6f7fcc0f
npm notice integrity:     sha512-HTXgrKLOM9gx0[...]0mbNDST0Z8UIQ==
npm notice total files:   23                                      
npm notice 
jupyterlab-latex-2.0.1.tgz

Fetching URL: https://registry.yarnpkg.com/@jupyterlab%2Flatex
Failed to fetch package metadata for '@jupyterlab/latex': URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))
Fetching URL: https://registry.yarnpkg.com/@jupyterlab%2Flatex
Failed to fetch package metadata for '@jupyterlab/latex': URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))
Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jupyterlab/labextensions.py", line 128, in start
    ans = self.run_task()

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jupyterlab/labextensions.py", line 167, in run_task
    return any([

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jupyterlab/labextensions.py", line 168, in <listcomp>
    install_extension(

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jupyterlab/commands.py", line 398, in install_extension
    return handler.install_extension(extension, pin=pin)

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jupyterlab/commands.py", line 620, in install_extension
    info = self._install_extension(extension, tempdir, pin=pin)

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jupyterlab/commands.py", line 1680, in _install_extension
    raise ValueError(msg)

ValueError: No version of @jupyterlab/latex could be found that is compatible with the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab                  Extension        Package
>=3.0.11 <3.1.0             >=2.0.0 <3.0.0   @jupyterlab/application
>=3.0.9 <3.1.0              >=2.0.0 <3.0.0   @jupyterlab/apputils
>=3.0.9 <3.1.0              >=2.0.0 <3.0.0   @jupyterlab/codeeditor
>=5.0.6 <5.1.0              >=4.0.0 <5.0.0   @jupyterlab/coreutils
>=3.0.11 <3.1.0             >=2.0.0 <3.0.0   @jupyterlab/docmanager
>=3.0.11 <3.1.0             >=2.0.0 <3.0.0   @jupyterlab/fileeditor
>=6.0.9 <6.1.0              >=5.0.0 <6.0.0   @jupyterlab/services
>=3.0.6 <3.1.0              >=2.0.0 <3.0.0   @jupyterlab/settingregistry
>=3.0.6 <3.1.0              >=2.0.0 <3.0.0   @jupyterlab/statedb
>=17.0.1 <18.0.0            >=16.8.6 <17.0.0 react
>=17.0.1 <18.0.0            >=16.8.6 <17.0.0 react-dom

Exiting application: lab

**Comment by bollwyvl** [comment]
As of https://github.com/jupyterlab/jupyterlab-latex/issues/154#issuecomment-928048027, the "prebuilt" distribution mechanism for JupyterLab 3.x is now preferred, where one would use any of:

```
python -m pip install jupyterlab-latex
mamba install -c conda-forge jupyterlab_latex
conda install -c conda-forge jupyterlab_latex
```
