### ISSUE TITLE
please add 3.2.0 on PyPI

### ISSUE THREAD

**Issue by jhgoebbert** [jupyterlab/jupyterlab-latex#218]
Hello and thank you for the new jupyterlab-latex 3.2.0  
It would be fantastic if you could add the new version 3.2.0 also on PyPI https://pypi.org/project/jupyterlab-latex/

**Comment by ruslaniv** [comment]
Agree! I can't install 3.2.0 and 3.1.0 would not install with jupyterlab 4.0 since 
```
The conflict is caused by:
    The user requested jupyterlab==4.0.3
    jupyterlab-latex 3.1.0 depends on jupyterlab<4 and >=3
```

**Comment by CharlieJ15420** [comment]
Is there any update on getting this version to PyPi? :-)

**Comment by miguelmarco** [comment]
If it is not uploaded to pypi, is there at least an easy way to install version 3.2.0?

**Comment by jhgoebbert** [comment]
Sure. Download the tar.gz from https://github.com/jupyterlab/jupyterlab-latex/archive/refs/tags/v3.2.0.tar.gz , extract it and do a `pip install` from that source directory.

**Comment by bnavigator** [comment]
Could you pleas "Release" 4.0.0 (with #211) both on GitHub as well as on PyPI?

**Comment by DManowitz** [comment]
Yes, is there a reason why nothing above 3.1.0 has been released to PyPI (and, therefore, also to conda-forge)?

**Comment by ktaletsk** [comment]
Version 4.1.1 is now live on PyPI: https://pypi.org/project/jupyterlab-latex/4.1.1/. Thanks for your patience, we had trouble setting up the release pipeline
