### ISSUE TITLE
please add 4.0.0 on PyPI

### ISSUE THREAD

**Issue by jhgoebbert** [jupyterlab/jupyterlab-latex#225]
Hello and thank you for the new jupyterlab-latex 4.0.0
It would be fantastic if you could add the new version 4.0.0 also on PyPI https://pypi.org/project/jupyterlab-latex/

**Comment by ktaletsk** [comment]
Version 4.1.1 is now live on PyPI: https://pypi.org/project/jupyterlab-latex/4.1.1/. Thanks for your patience 🙏

**Comment by jhgoebbert** [comment]
Cool !!! Great !!!
