### ISSUE TITLE
Not supported on windows

### ISSUE THREAD

**Issue by t-makaro** [jupyterlab/jupyterlab-latex#41]
Specifically because tornado support for windows is not official/experimental.

```from tornado.process import Subprocess```

Going down this rabbit hole, I found that it relies on a package called "fcntl" which is not available on windows. A shame as I'd really like to start using this extension.

**Comment by ian-r-rose** [comment]
Ouch, thanks for tracking that down @t-makaro! We are using `tornado.Subprocess` as it supports asynchronous execution. We would really like to support Windows, however, so I think we may decide that it is better to have Windows support than an async server extension.

**Comment by mpacer** [comment]
In talking with @ian-r-rose offline… I think what we're going to try to do is figure out some way to shim the synchronous subprocess call to have an api similar to the async one from tornado, that way we can have the async functionality on OSX and Unix, but it would work for Windows synchronously via the shim.

**Comment by t-makaro** [comment]
I've updated to the latest version, and "Show LaTeX Preview" is no longer appearing in the right click menu. The ```jupyter serverextension list```, ```jupyter labextension list```, and ```jupyter labextension check @jupyterlab/latex``` commands confirm that I've enabled the latest version.

**Comment by ian-r-rose** [comment]
I just took this screenshot on Windows 10:
![image](https://user-images.githubusercontent.com/5728311/35528799-d9ebd538-04e3-11e8-9155-751eb3004ad7.png)
Can you confirm that you are running `@jupyterlab/latex` v0.2.0, `jupyterlab_latex`  v0.2.0, and JupyterLab v0.31.2?

**Comment by t-makaro** [comment]
I was on Jupyterlab 0.31.1. I've updated, and it's working now. I've just got one further question. Why don't I have syntax highlighting for .tex files like the image in the readme shows?

**Comment by mpacer** [comment]
I think that's an issue with codemirror noticing the .tex extension, if you set the language manually you should get highlighting.

**Comment by t-makaro** [comment]
How might I do that?
