### ISSUE TITLE
jupyter-config/jupyter_notebook_config.d is not included in editable installs

### ISSUE THREAD

**Issue by mpacer** [jupyterlab/jupyterlab-latex#50]
If you run `pip install -e .` it will not place `jupyter-config/jupyter_notebook_config.d` in any directory… furthermore it will overwrite any config that has been placed there.

For now, if you want to work on an editable install you still need to run 

```
jupyter serverextension enable --sys-prefix jupyterlab_latex
```

**Comment by bollwyvl** [comment]
Deploying  `data_files` in an editable install isn't supported via `setup.py develop` or `pip install -e` or any known functional replacement from `poetry`, `flit`, etc. at this time. and is not specific to this package... https://github.com/jupyter-server/jupyter_server/issues/351
