### ISSUE TITLE
synctex

### ISSUE THREAD

**Issue by t-makaro** [jupyterlab/jupyterlab-latex#56]
Feature request. Compiling latex with the -synctex=1 flag allows TeXStudio (and others) to link the source code and pdf so one can right click on the pdf and "go to source". This is the main thing I miss when using this extension compared to TeXStudio. I'd switch over completely if this extension had synctex support.

**Comment by ian-r-rose** [comment]
I agree, this would be very cool. I am not sure just yet how easy it would be to do it.

**Comment by AlexandreDecan** [comment]
I agree with that feature. I don't know how easy/hard it is, however. 
Maybe the current implementation in atom-latex could provide some hints?
https://github.com/James-Yu/Atom-LaTeX/blob/master/lib/locator.coffee
