### ISSUE TITLE
Enable resize/zoom on the PDF

### ISSUE THREAD

**Issue by joshjob42** [jupyterlab/jupyterlab-latex#62]
In the standard PDF viewer in JupyterLab (at least in Chrome, my only available browser) one can easily zoom in and out on the PDF. This is helpful on smaller screens such as ultrabooks since one can zoom in enough to get rid of the margins and just be looking at the text area. Right now, this extension does not support the same, so one always sees the entire page of the PDF. 

It would be tremendously useful if one could still zoom in and out of the PDF, either by using the standard PDF viewer (perhaps with modifications) or adding the feature directly into this packages existing PDF viewer.

**Comment by ian-r-rose** [comment]
Agreed, it would definitely be nice to build out some UIs for the PDF.js viewer.

This may involve building them ourselves, or swapping in a more full-featured renderer for our bare-bones one.

**Comment by ian-r-rose** [comment]
Note that the reason we don't use the browser-native PDF viewer is that it doesn't provide us any way to programmatically control the view (scaling, scrolling, etc).
