### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by wolfv** [jupyterlab/jupyterlab-latex#73]
Would you guys mind if I make a conda package? Couldn't find one ... or does it exist?

**Comment by mpacer** [comment]
You mean on the conda-forge channel, I'm guessing? 

You're welcome to, but would you include @ian-r-rose and I as maintainers of it, that way when we cut new releases we have the ability to actually push out a new conda-forge release with our pypi and npm releases.

**Comment by bollwyvl** [comment]
As of 3.1.0, a single `conda install -c conda-forge jupyterlab_latex` will bring along everything (except a working latex environment :rofl: )

https://anaconda.org/conda-forge/jupyterlab_latex/files?version=3.1.0
