### ISSUE TITLE
How to make sure the tex software is in the same environment as the notebook server?

### ISSUE THREAD

**Issue by leeweizhe1993** [jupyterlab/jupyterlab-latex#77]
![image](https://user-images.githubusercontent.com/32242263/39537832-59b3c73a-4e6d-11e8-961c-c1e6ce9f6c9a.png)

**I just installed Texlive today and I put it in the root directory of my D drive, the file path is “D:\texlive\2018\bin\win32\texworks.exe”, and the working path of my lab is "D:\Git\self_project\Jupyter". What should I do if I want to edit tex file in my lab?**

![image](https://user-images.githubusercontent.com/32242263/39538071-1b50f20a-4e6e-11e8-93ca-b2892f00f742.png)
![image](https://user-images.githubusercontent.com/32242263/39538253-c7930ec2-4e6e-11e8-8fb1-daeef732e822.png)

**Comment by ian-r-rose** [comment]
A `.tex` file should be plain text. That error message is usually shown when you try to open a binary file that we don't know how to read in. Can you verify that your `qftt.tex` is plain text (i.e., open it in a text editor like notepad)?

**Comment by leeweizhe1993** [comment]
![image](https://user-images.githubusercontent.com/32242263/39539320-de5410a4-4e71-11e8-85aa-2e2f572747a8.png)
I guess the reason for the error may be the .tex file is coded in GB2312 format.

**Comment by ian-r-rose** [comment]
Ah, yes, that does sound like it might be a problem. Would it be possible to check if a `utf-8` encoding works for your files?

**Comment by leeweizhe1993** [comment]
![image](https://user-images.githubusercontent.com/32242263/39559653-64bc0cde-4eca-11e8-81ec-d218aaedfd13.png)
Worked after converting to UTF-8 encoding, THX! :laughing:

**Comment by ian-r-rose** [comment]
Glad to hear it @leeweizhe1993! Closing as resolved.
