### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by luciofaso** [jupyterlab/jupyterlab-latex#83]
I tried to install this package using the command

```
pip install jupyterlab_latex
```

but I get the following message

```
Could not find a version that satisfies the requirement jupyterlab_latex (from versions: )
No matching distribution found for jupyterlab_latex
```

**Comment by bourque** [comment]
@luciofaso Are you sure you are using python >= 3.6?

**Comment by wbadart** [comment]
Might just be a typo in the README; searching pypi doesn't show any hits for `jupterlab_latex` with an *underscore* but it does show a package (from the jupyterlab team) called [`jupterlab-latex`](https://pypi.org/project/jupyterlab-latex/) with a *hyphen*.

**Comment by bollwyvl** [comment]
README is now accurate.
