### ISSUE TITLE
Win10 >>  install nodejs and npm?

### ISSUE THREAD

**Issue by lonesome-data** [jupyterlab/jupyterlab-latex#85]
@mpacer @ian-r-rose 
hey j-lab superstars.  do i need to clone first?  here is where I am in my Win10 OS
![image](https://user-images.githubusercontent.com/25334926/42739417-9770e2a0-885c-11e8-8f1b-df22dd7b405e.png)
do i really need to install nodejs and npm?

thanks!
@lonesome-data

**Comment by ian-r-rose** [comment]
Hi @lonesome-data! Yes, in order to install extensions with JupyterLab you need to have node installed (for the moment you should aim for node 8 or 9).

If you are running Anaconda, you should be able to install it using `conda install -c conda-forge nodejs`

**Comment by lonesome-data** [comment]
@ian-r-rose thank you for the prompt reply.  i'll give your input a try and close issue if resolved.

**Comment by lonesome-data** [comment]
@ian-r-rose  
the conda-forge install of nodejs worked.  thank you.

now i am stuck at extension install...
![image](https://user-images.githubusercontent.com/25334926/42912919-c86666f4-8aa6-11e8-8f30-0b3cf1b4777e.png)

guess i will have to tackle this tonight with a beer

**Comment by ian-r-rose** [comment]
The extension name is `@jupyterlab/latex` not `@jupyter/latex`.

**Comment by lonesome-data** [comment]
jupyter-latex install now sticking on webpack 
![image](https://user-images.githubusercontent.com/25334926/42956339-997c3da8-8b34-11e8-89e0-be701cab56f1.png)
because this is captured in another open issue, closing this one...
