### ISSUE TITLE
Jupyterlab-latex installed but error says it's not

### ISSUE THREAD

**Issue by thongnnguyen** [jupyterlab/jupyterlab-latex#87]
Hi, I'm running a jupyterlab 0.32.1 on Ubuntu 16.04, Anaconda 4.5.8

Output of `jupyter labextension list`

```shell
JupyterLab v0.32.1
Known labextensions:
   app dir: /opt/anaconda3/share/jupyter/lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.35.0  enabled  OK
@jupyterlab/hub-extension
        @jupyterlab/hub-extension v0.9.0  enabled  OK
@jupyterlab/latex
        @jupyterlab/latex v0.3.1  enabled  OK
@oriolmirosa/jupyterlab_materialdarker
        @oriolmirosa/jupyterlab_materialdarker v0.3.1  enabled  OK
jupyterlab-drawio
        jupyterlab-drawio v0.2.0  enabled  OK
```

But when I try to preview a .tex file, I got the error:

```
Server Extension Error
You probably do not have jupyterlab_latex installed or enabled. Please, run "pip install -U jupyterlab_latex." If that does not work, try "jupyter serverextension enable --sys-prefix jupyterlab_latex".
```

I have `xetex` installed in the same conda environment by

```
conda install -c conda-forge texlive-core 
```

Any insights where I did wrong? When I tried 

```
sudo jupyter serverextension enable --sys-prefix jupyterlab_latex
```
I got

```bash
Enabling: jupyterlab_latex
- Writing config: /opt/anaconda3/etc/jupyter
    - Validating...
Error loading server extension jupyterlab_latex
      X is jupyterlab_latex importable?
```

**Comment by ian-r-rose** [comment]
You also need to install the corresponding python package. Try entering
```bash
pip install jupyterlab_latex
```

**Comment by ian-r-rose** [comment]
Closing as answered. If you are still having troubles, feel free to comment here and we can reopen.

**Comment by andreas-h** [comment]
I am having exactly the same problem here.  When right-clicking *Show LaTeX preview* I get `Server Extension ErrorYou probably do not have jupyterlab_latex installed or enabled. Please, run "pip install -U jupyterlab_latex." If that does not work, try "jupyter serverextension enable --sys-prefix jupyterlab_latex".`.  When trying to install the serverextension I get the same error as @thongnnguyen 

I'm on JupyterLab 1.1.1 behind JupyterHub 1.0

**Comment by mgbvox** [comment]
`pip install -U jupyter_latex`
results in:
'ERROR: Could not find a version that satisfies the requirement jupyter_latex (from versions: none)
ERROR: No matching distribution found for jupyter_latex'

There does, however, exist a pip distribution for [**jupyterlab-latex**](https://pypi.org/project/jupyterlab-latex/2.0.0/) (note the hyphen). 

Is this what we should be using?
